# Copyright 2026 luginf
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Hand written notes for words that site/*.html does not document.

Used by tools/words_reference.py. Each entry is  name: (stack effect, description).
The names of standard (ANS Forth) words are in ANS, so they need no note.
"""

NOTES = {
  '#!': ('( -- )', 'Skips the rest of the line, so a script can start with `#! /usr/bin/env ueforth`. Immediate.'),
  '#fs': ('( r -- )', 'Pictured numeric output for a float: adds its digits (and a minus sign) to the number being built. Used by `f.`.'),
  '+to': ('( n "name" -- )', 'Adds n to a `value` or a local: `1 +to count`.'),
  '-rot': ('( a b c -- c a b )', 'The reverse of `rot`.'),
  '3dup': ('( a b c -- a b c a b c )', 'Duplicates the top three cells.'),
  '4*': ('( n -- n*4 )', 'Multiplies by 4.'),
  '4/': ('( n -- n/4 )', 'Divides by 4 with an arithmetic shift.'),
  '<=': ('( a b -- f )', 'True if a is less than or equal to b.'),
  '>=': ('( a b -- f )', 'True if a is greater than or equal to b.'),
  '>flags': ('( xt -- n )', 'The flag byte of a definition (bit 0 is set for immediate words).'),
  '>flags&': ('( xt -- a )', 'The address of the flag byte of a definition.'),
  '>link': ('( xt -- xt2 )', 'The definition that comes before this one in its vocabulary.'),
  '>link&': ('( xt -- a )', 'The address of the link field of a definition.'),
  '>name': ('( xt -- a n )', 'The name of a definition, as a string.'),
  '>params': ('( xt -- n )', 'The number of parameter cells a definition keeps in its header.'),
  '>size': ('( xt -- n )', 'The size in bytes of a definition header: name, flags, link and its parameter cells.'),
  'aft': ('( -- )', 'eForth loop word: in `n for A aft B then C next`, A runs only the first time round, B every other time, C every time.'),
  'argc': ('( -- n )', 'The number of command line arguments.'),
  'argv': ('( n -- a n )', 'Command line argument number n, as a string (0 is the program, 1 the script).'),
  'arshift': ('( n u -- n2 )', 'Shifts n right by u bits, keeping the sign.'),
  'assert': ('( f -- )', 'Testing framework: throws if the flag is false. See `common/testing.fs`.'),
  'bg': ('( n -- )', 'Sets the terminal background color, 0 to 255 (ANSI escape sequence).'),
  'fg': ('( n -- )', 'Sets the terminal text color, 0 to 255 (ANSI escape sequence).'),
  'normal': ('( -- )', 'Resets the terminal colors and attributes.'),
  'n.': ('( n -- )', 'Prints a number without a trailing space.'),
  'set-title': ('( a n -- )', 'Sets the title of the terminal window.'),
  'binary': ('( -- )', 'Sets the number base to 2.'),
  'octal': ('( -- )', 'Sets the number base to 8.'),
  'block-fid': ('( -- n )', 'Value. The file handle of the file that holds the blocks, -1 if none.'),
  'block-id': ('( -- n )', 'Value. The number of the block now in the block buffer, -1 if none.'),
  'cell': ('( -- n )', 'The size of a cell in bytes.'),
  'cell/': ('( n -- n2 )', 'Divides a size in bytes by the size of a cell.'),
  'close-dir': ('( dh -- ior )', 'Closes a directory opened with `open-dir`.'),
  'open-dir': ('( a n -- dh ior )', 'Opens a directory by name.'),
  'read-dir': ('( dh -- a n )', 'The name of the next entry of an open directory, or 0 at the end.'),
  'context': ('( -- a )', 'The address of the top of the search order.'),
  'current': ('( -- a )', 'The address of the variable that says which vocabulary `definitions` go to.'),
  'copy': ('( from to -- )', 'Copies a block to another block.'),
  'default-key': ('( -- c )', 'The standard input `key` of the platform, what `key` does by default.'),
  'default-type': ('( a n -- )', 'The standard output `type` of the platform, what `type` does by default.'),
  'default-use': ('( -- )', 'Deferred word run to open the default block file, `blocks.fb`.'),
  'echo': ('( -- a )', 'Variable. Typed characters are echoed while it is true.'),
  'extract': ('( n base -- n2 c )', 'Pictured numeric output: splits off the last digit of n.'),
  'hld': ('( -- a )', 'Variable. The position in the pictured numeric output buffer.'),
  'str': ('( n -- a u )', 'Converts a signed number to a string in the current base.'),
  'file-exists?': ('( a n -- f )', 'True if the named file can be opened.'),
  'form': ('( -- h w )', 'The height and width of the terminal, in characters.'),
  'forth-builtins': ('( -- )', 'The vocabulary at the bottom of `forth`, holding the words defined in C. They are moved into `forth` when the system starts.'),
  'fp0': ('( -- a )', 'The float stack pointer at the start.'),
  'sp0': ('( -- a )', 'The data stack pointer at the start.'),
  'rp0': ('( -- a )', 'The return stack pointer at the start.'),
  'sp@': ('( -- a )', 'The data stack pointer.'),
  'sp!': ('( a -- )', 'Sets the data stack pointer.'),
  'rp@': ('( -- a )', 'The return stack pointer.'),
  'rp!': ('( a -- )', 'Sets the return stack pointer.'),
  'for': ('( n -- )', 'eForth counted loop: `n for ... next` runs the body n+1 times, `r@` gives the count from n down to 0.'),
  'next': ('( -- )', 'Ends a `for` loop.'),
  'included?': ('( a n -- f )', 'True if the file was already included.'),
  'k': ('( -- n )', 'The index of the third enclosing `do` loop, after `i` and `j`.'),
  'l!': ('( n a -- )', 'Stores the low 32 bits of n at address a.'),
  'w!': ('( n a -- )', 'Stores the low 16 bits of n at address a.'),
  'sl@': ('( a -- n )', 'Fetches a signed 32 bit number.'),
  'ul@': ('( a -- u )', 'Fetches an unsigned 32 bit number.'),
  'sw@': ('( a -- n )', 'Fetches a signed 16 bit number.'),
  'uw@': ('( a -- u )', 'Fetches an unsigned 16 bit number.'),
  'latestxt': ('( -- xt )', 'The execution token of the word defined last.'),
  'needs': ('( "name" -- )', 'Includes a file unless it was already included.'),
  'nl': ('( -- n )', 'The newline character, 10.'),
  'non-block': ('( fh -- ior )', 'Puts an open file or socket in non-blocking mode.'),
  'ok': ('( -- )', 'Prints the ` ok` after a line is interpreted.'),
  'prompt': ('( -- )', 'Deferred word that prints the input prompt.'),
  'pause?': ('( -- f )', 'True if another task is waiting to run.'),
  'postpone,': ('( xt -- )', 'Compiles a word the way `postpone` would.'),
  'r~': ('( "string~" -- a n )', 'Raw string ending with `~`, on several lines if needed: `r~ text with | bars ~`. Like `r"` and `r|`, it needs no escapes.'),
  'startswith?': ('( a n a2 n2 -- f )', 'True if the first string starts with the second.'),
  'str=': ('( a n a2 n2 -- f )', 'True if two strings are equal.'),
  'tib': ('( -- a )', 'The address of the terminal input buffer.'),
  'transfer{': ('( -- )', 'Starts a list of names to copy into the current vocabulary, ended by `}transfer`: `transfer{ dup drop }transfer`.'),
  '}transfer': ('( -- )', 'Ends a `transfer{` list.'),
  'u/mod': ('( u u2 -- rem quot )', 'Unsigned division with the remainder.'),
  'used': ('( -- n )', 'The number of bytes of the dictionary in use.'),
  '{': ('( "names" -- )', 'Declares locals: `{ a b -- c }`. The values are taken from the stack; what follows `--` is only a comment.'),
  # vocabularies
  'ansi': ('( -- )', 'Vocabulary of terminal escape sequences: colors, cursor, screen.'),
  'editor': ('( -- )', 'Vocabulary of the block editor.'),
  'graphics': ('( -- )', 'Lazy loaded generic graphics interface (a window and a back buffer, on X11 or the web). See `common/graphics.fs`.'),
  'httpd': ('( -- )', 'Lazy loaded HTTP server. See `site/posix_common.html`.'),
  'internals': ('( -- )', 'Vocabulary of the inner workings of the system.'),
  'posix': ('( -- )', 'Vocabulary of the system calls and constants of Linux and macOS.'),
  'recognizers': ('( -- )', 'Vocabulary of the recognizers, which decide what to do with a word that is not found.'),
  'sockets': ('( -- )', 'Lazy loaded BSD sockets.'),
  'streams': ('( -- )', 'Vocabulary of byte streams (ring buffers).'),
  'structures': ('( -- )', 'Vocabulary for building C-style structures.'),
  'tasks': ('( -- )', 'Vocabulary of the cooperative tasks.'),
  'telnetd': ('( -- )', 'Lazy loaded telnet server.'),
  'termios': ('( -- )', 'Vocabulary of terminal handling.'),
  'visual': ('( -- )', 'Lazy loaded visual (full screen) editor.'),
  'web-interface': ('( -- )', 'Lazy loaded web UI server.'),
  'x11': ('( -- )', 'Lazy loaded X11 bindings.'),
  'sdl2': ('( -- )', 'Lazy loaded SDL2 short words for games. See `posix/SDL2.md`.'),
  'sdl2-image': ('( -- )', 'Lazy loaded SDL2_image sprites. See `posix/SDL2.md`.'),
  'sdl2-ttf': ('( -- )', 'Lazy loaded SDL2_ttf text. See `posix/SDL2.md`.'),
  'sdl2-mixer': ('( -- )', 'Lazy loaded SDL2_mixer sound, music and soundfont. See `posix/SDL2.md`.'),
  'sdl2-abc': ('( -- )', 'Lazy loaded reader and player of tunes in ABC notation. See `posix/SDL2.md`.'),

  # words that only have a stack comment or a C/JS binding, filled by hand
  'asm': ('( -- )', 'Vocabulary of the inline assembler for the native CPU. See `common/assembler.fs`.'),
  '1/f': ('( r -- r2 )', 'The inverse of a float, 1/r.'),
  'afliteral': ('( r -- )', 'Compiles a float as a literal. Immediate.'),
  'f<=': ('( r1 r2 -- f )', 'True if r1 is less than or equal to r2.'),
  'f<>': ('( r1 r2 -- f )', 'True if r1 and r2 are different.'),
  'f=': ('( r1 r2 -- f )', 'True if r1 and r2 are equal.'),
  'f>': ('( r1 r2 -- f )', 'True if r1 is greater than r2.'),
  'f>=': ('( r1 r2 -- f )', 'True if r1 is greater than or equal to r2.'),
  'fnip': ('( ra rb -- rb )', 'Drops the float below the top of the float stack.'),
  'fp!': ('( a -- )', 'Sets the float stack pointer.'),
  'fp@': ('( -- a )', 'The float stack pointer.'),
  'pi': ('( -- r )', 'The constant pi.'),
  'sf,': ('( r -- )', 'Compiles a float into the dictionary.'),
  'sfloat': ('( -- 4 )', 'Constant, the size in bytes of a float (single precision).'),
  'dlsym': ('( module name-z -- fn )', "C `dlsym`: the address of a symbol in a shared library, or of the main program's symbols when module is 0."),
  '>name-length': ('( xt -- n )', 'The length in bytes of the name of a definition.'),
  'call': ('( xt -- )', 'Calls a foreign function through the FFI. Used by `sofunc`, `sysfunc` (POSIX) and `JSWORD:` (web).'),
  'colors': ('( -- )', 'Web build: prints all 256 terminal colors, to see what `fg` and `bg` give.'),
  'web': ('( -- )', 'Web build: the vocabulary of the words specific to the browser (the JS interpreter, `JSWORD:`...).'),
}
